### ISSUE TITLE
Error on siebel log file loading

### ISSUE THREAD

**Issue by pmvkarthik** [prashanth1k/COGSiebelLogaliserWF#1]
Getting below error while loading siebel log file from server
Unable to load Local siebel log file too.
PLease find error below being faced.
---------------------------
Error
---------------------------
Error occurred. COGSiebelLogaliserWF StartIndex cannot be less than zero.

Parameter name: startIndex
---------------------------
OK   
---------------------------

**Comment by prashanth1k** [comment]
Surprised that someone is still using this :). It's been some time since I worked on Siebel, but will see what I can do.

Do you have a sample log file that I can replicate this with?

**Comment by prashanth1k** [comment]
No response. Unable to replicate :|

**Comment by pmvkarthik** [comment]
sorry was unable to provide sample file during that time because of COVID etc.., but i shared it now with new defect logged.
