### ISSUE TITLE
getting error "Error occurred. COGSiebelLogaliserWF StartIndex cannot be less than zero."

### ISSUE THREAD

**Issue by pmvkarthik** [prashanth1k/COGSiebelLogaliserWF#2]
Getting below error while loading latest Siebel IP21.12/ 8.1 logs to the log analizer. please help rectify the same or please provide guidance on same to do further development on it to rectify this problem.

attached working and non working log files here.

[eCommunicationsObjMgr_enu_0034_35651631_working sample log file.log](https://github.com/user-attachments/files/17113177/eCommunicationsObjMgr_enu_0034_35651631_working.sample.log.file.log)

Please help to rectify same 

Error occurred. COGSiebelLogaliserWF StartIndex cannot be less than zero.

Parameter name: startIndex

**Comment by pmvkarthik** [comment]
non working log file

**Comment by pmvkarthik** [comment]
[eCommunicationsObjMgrSSO_enu_0037_38797362.zip](https://github.com/user-attachments/files/17113337/eCommunicationsObjMgrSSO_enu_0037_38797362.zip)
attached non working log file here for reference.

**Comment by prashanth1k** [comment]
Hi there. Sorry, I may not be able to help here - I have moved away from Siebel and desktop programming. Will try to whip something together on some weekend. What do you specifically look out for - performance, error summaries or anything else?

**Comment by prashanth1k** [comment]
Archiving the repo. Not planning any fixes here.
